{% set python_min = "3.11" %}
{% set name = "conda-forge-tick" %}
{% set version = "2025.5.101" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/cf-scripts/archive/refs/tags/{{ version }}.tar.gz
  sha256: ac68490e6997872d7a4cb362bda3b929e3cc053217de54269dd1f315b0155f26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - conda-forge-tick = conda_forge_tick.cli:main
    - conda-forge-tick-container = conda_forge_tick.container_cli:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm >=8
  run:
    - python >={{ python_min }}
    - attrs
    - backoff
    - cachecontrol
    - cachetools
    - click
    - conda
    - conda-lock
    - conda-forge-feedstock-check-solvable >=0.8.0
    - conda-forge-pinning
    - conda-libmamba-solver
    - conda-forge-metadata >=0.3.0
    - conda-forge-feedstock-ops >=0.10.2
    - conda-package-handling
    - conda-smithy >=3.34.1
    - conda-build >=3.24.0
    - curl
    - depfinder
    - distributed
    - feedparser
    - frozendict
    - git
    - github3.py
    - grayskull >=2.5
    - jinja2
    - lockfile
    - mamba >=0.23
    - msgpack-python
    - networkx !=2.8.1
    - numpy
    - orjson
    - packaging
    - psutil
    - pydantic
    - pydantic-extra-types
    - pydantic-settings
    - pygithub
    - pymongo
    - pynamodb
    - python-dateutil
    - python-graphviz
    - rattler-build >=0.35.4
    - rattler-build-conda-compat >=1.3.2,<2
    - requests
    - ruamel.yaml
    - ruamel.yaml.jinja2
    - scipy
    - stopit
    - streamz
    - tar
    - tqdm
    - wget
    - wurlitzer
    - yaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - conda_forge_tick
  commands:
    - python -c "import conda_forge_tick; assert conda_forge_tick.__version__ == '{{ version }}'"
    - conda-forge-tick --help
    - conda-forge-tick-container --help

about:
  home: https://github.com/regro/cf-scripts
  summary: 'Flagship repo for cf-regro-autotick-bot'
  license: BSD-3-Clause AND MIT
  license_file: License

extra:
  recipe-maintainers:
    - beckermr
    - regro-cf-autotick-bot  # bot account controlled by the bot team
