{% set name = "conda-forge-tick" %}
{% set version = "2024.8.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/cf-scripts/archive/refs/tags/{{ version }}.tar.gz
  sha256: f7ed7ac753012dd89f57892f2ef6c1957258a229782d86f0a41ae437619b4fbf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
    - setuptools_scm >=8
    - build
  run:
    - python >=3.11
    - attrs
    - backoff
    - cachecontrol
    - cachetools
    - click
    - conda
    - conda-lock
    - conda-forge-feedstock-check-solvable >=0.4.0
    - conda-forge-pinning
    - conda-libmamba-solver
    - conda-forge-metadata >=0.3.0
    - conda-package-handling
    - conda-smithy >=3.34.1
    - conda-build >=3.24.0
    - curl
    - depfinder
    - distributed
    - feedparser
    - frozendict
    - git
    - github3.py
    - grayskull >=2.5
    - jinja2
    - lockfile
    - mamba >=0.23
    - msgpack-python
    - networkx !=2.8.1
    - numpy
    - packaging
    - psutil
    - pydantic
    - pydantic-extra-types
    - pygithub
    - pymongo
    - pynamodb
    - python-dateutil
    - python-graphviz
    - python-rapidjson
    - rattler-build
    - requests
    - ruamel.yaml
    - ruamel.yaml.jinja2
    - scipy
    - stopit
    - streamz
    - tar
    - tqdm
    - wget
    - wurlitzer
    - yaml

test:
  imports:
    - conda_forge_tick
  commands:
    - python -c "import conda_forge_tick; assert conda_forge_tick.__version__ == '{{ version }}'"

about:
  home: https://github.com/regro/cf-scripts
  summary: 'Flagship repo for cf-regro-autotick-bot'
  license: BSD-3-Clause AND MIT
  license_file: License

extra:
  recipe-maintainers:
    - beckermr
    - regro-cf-autotick-bot  # bot account controlled by the bot team
